<script type="text/template" id="instant-stats-template">
    <div class="py-2">
        {{#hasOneResult}}<strong>1</strong>
        <span class="text-sm leading-5 text-gray-700 tracking-wider">
        <?= $escaper->escapeHtml(__('Item')); ?>
        </span>
        {{/hasOneResult}}
        {{#hasManyResults}}
        <span class="text-sm leading-5 text-gray-700 tracking-wider">
            <?= $escaper->escapeHtml(__('Items')); ?>
        </span>
        <span class="text-sm leading-5 text-gray-700 tracking-wider" itemprop="numberOfItems">
        {{first}}-{{last}} <?= $escaper->escapeHtml(__('of')); ?>
        </span>
        <span class="text-sm leading-5 text-gray-700 tracking-wider" itemprop="numberOfItems">{{nbHits}}</span>
        {{/hasManyResults}}
        {{^hasNoResults}}
        <?= $escaper->escapeHtml(__('in')); ?> {{seconds}} <?= $escaper->escapeHtml(__('seconds')); ?>
        {{/hasNoResults}}
    </div>
</script>
