<?php

use Blackbird\HyvaAlgoliaSearch\ViewModel\InstantSearchViewModel;

/**
 * @var \Hyva\Theme\Model\ViewModelRegistry $viewModels
 */
/** @var \Algolia\AlgoliaSearch\Block\Widget\LookingSimilar $block */
$isEnabled = $block->isLookingSimilarEnabled();
$uniqueToken = $block->generateUniqueToken();

/** @var InstantSearchViewModel $viewModel */
/** @var \Magento\Framework\Escaper $escaper */
$viewModel = $viewModels->require(InstantSearchViewModel::class);

if ($isEnabled):
    $lsContainer =  'lsItems' . $block->generateUniqueToken(); ?>
    <div id="<?= $escaper->escapeHtmlAttr($lsContainer) ?>" class="LSItem recommend-component"></div>
    <script>
        function initRecommendLS<?= $uniqueToken ?>() {
            Promise.all([
                <?php foreach($viewModel->getRecommendedLSScripts() as $script) :?>
                blackbird.loadExternalResource("<?= $script ?>"),
                <?php endforeach; ?>]
            ).then(data => {
                window.addEventListener('init-algolia-LS-done', function () {
                    initAlgoliaRecommendedLS("<?= $escaper->escapeJs($lsContainer) ?>", "<?= $escaper->escapeJs($block->getData('numOfLookingSimilarItem')) ?>", "<?= $escaper->escapeJs($block->getProductIds()) ?>");
                });

                window.dispatchEvent(new CustomEvent('init-algolia-LS'));
            });
        }
        window.addEventListener('DOMContentLoaded', function (){
            initRecommendLS<?= $uniqueToken ?>();
        });

    </script>
<?php endif; ?>
